
version: '3.8'
services:
  postgres:
     image: postgres:10.3
     restart: always
     environment:
      - POSTGRES_USER=ndeanon25
      - POSTGRES_PASSWORD=password123
     volumes:
       - postgres:/var.lib/postgres/data
     ports:
      - '5432:5432'
volumes:
  postgres: